config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  resources :posts
  resources :users
  resources :roles
  resources :permissions
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
    user.role.permissions.each do |permission|
      if permission.subject_class == "all"
        can permission.action.to_sym, permission.subject_class.to_sym
      else
        can permission.action.to_sym, permission.subject_class.constantize
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :role

  ATTRIBUTES_PARAMS = [:subject_class, :action, :role_id]

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :permissions
  has_many :users

  ATTRIBUTES_PARAMS = [:name]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  belongs_to :role
  delegate :name, to: :role
  def admin?
     self.name == 'Admin'
  end

  def manager?
     self.name == 'Manager'
  end
  def user?
     self.name == 'User'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected


  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = "Access denied. You are not authorized to access the requested page."
    redirect_to root_path
   end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role_id])
  end

  def self.permission
    return name = self.name.gsub("Controller","").singularize.split("::").last.constantize.name rescue nil
  end

  def current_ability
    @current_ability ||= Ability.new current_user
  end

  def load_permissions
    @current_permissions = current_user.role.permissions.collect{|p| [p.subject_class, p.action]}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  load_and_authorize_resource
  before_action :load_permissions
  before_action :set_permission, only: %i[ show edit update destroy ]


  def new
    @permission = Permission.new
    @roles = Role.all.order(name: :asc)
  end

  def edit
    @roles = Role.all.order(name: :asc)
  end

  def create
    @permission = Permission.new(permission_params)

    respond_to do |format|
      if @permission.save
        format.html { redirect_to roles_path, notice: "permission was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @permission.update(permission_params)
        format.html { redirect_to roles_path, notice: "permission was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @permission.destroy

    respond_to do |format|
      format.html { redirect_to permissions_url, notice: "permission was successfully destroyed." }
    end
  end

  private
    def set_permission
      @permission = Permission.find(params[:id])
    end

    def permission_params
      params.require(:permission).permit(:subject_class, :action, :role_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :load_permissions
  before_action :set_post, only: %i[ show edit update destroy ]
  def index
    @posts = Post.all
  end

  def show; end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      @post.user_id = current_user.id

      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :is_manager
  before_action :find_role, only: [:show, :edit, :update]

  def index
    @roles = Role.all
  end

  private
  def is_manager
    redirect_to root_path unless current_user.manager?
  end

  def find_role
    @role = Role.find params[:id]
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      if get?
        raise e
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :load_permissions
  before_action :set_user, only: %i[edit update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    respond_to do |format|
      if user.save
        format.html { redirect_to users_path, notice: "User was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @roles = Role.all.order(name: :asc)
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: "User was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :role_id, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  module ApplicationHelper
    def errors_for(model, key)
      tag.div(class: "mt-2 form-error") do
        model.errors.messages_for(key).join(", ")
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Welcome</h1>
<div class="d-flex">
  <%= link_to "Get Started", posts_path, class:'btn btn-outline-success mx-2' %>
  <%= link_to "Manage Users", users_path, class:'btn btn-outline-info mx-2'if can? :manage, current_user%>
  <%= link_to "Manage Permissions", roles_path, class:'btn btn-outline-info mx-2'if can? :manage, current_user%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
     integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <%if flash[:notice].present? %>
      <p class="notice bg-success p-2 "><%= notice %></p>
    <% end %>
    <% if flash[:alert].present? %>
      <p class="alert bg-danger p-2"><%= alert %></p>
    <% end %>
    <div class="container" data-controller="notification">
      <%= yield %>
    </div>
  </body>
</html>

app/views/permissions/_form.html.erb
<%= form_with(model: permission) do |form| %>
  <% if permission.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(permission.errors.count, "error") %> prohibited this permission from being saved:</h2>

      <ul>
        <% permission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    Resource
    <%= form.select :subject_class, options_for_select({ 'All': 'All',  'User': 'User',
                        'Post': 'Post', 'Permission': 'Permission' }, permission.subject_class),
                      { include_blank: true },
                      { class: 'form-control select2' } %>

  </div>

  <div class="form-group mt-2">
      Privilege Level
    <%= form.select :action, options_for_select({ 'Manage': 'manage',  'Read': 'read',
                        'Update': 'update', 'Destroy': 'delete' }, permission.action),
                      { include_blank: true },
                      { class: 'form-control select2' } %>
  </div>

   <div class="form-group mt-2">
    Role
    <%= form.select :role_id, options_from_collection_for_select(@roles, 'id', 'name', permission&.role&.id),
                                              {}, class:'form-control',
                                              required: true %>
  </div>

  <div class="form-group mt-2">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/permissions/edit.html.erb
<div class="card col-6 p-4">
  <h1>Editing Permision</h1>
    <%= render "form", permission: @permission %>
  <br>

  <div>
    <%= link_to "Back to permissionss", roles_path, class:"btn btn-outline-secondary" %>
  </div>
</div>

app/views/permissions/new.html.erb
<div class="card col-6 p-4">
  <h1>New Permission</h1>

  <%= render "form", permission: @permission %>

  <br>

  <div>
    <%= link_to "Back to Permisions", roles_path, class:"btn btn-outline-secondary" %>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group mt-2">
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content, class:"form-control" %>
  </div>

  <div class="form-group mt-2">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

  <p>
    <span><strong>Author</strong>
   <i><%= post.user.name%></i></span>
  </p>

</div>

app/views/posts/edit.html.erb
<div class="card col-6 p-4">
  <h1>Editing post</h1>

  <%= render "form", post: @post %>

  <br>

  <div>
    <%= link_to "Show this post", @post, class:"btn btn-outline-info" %> |
    <%= link_to "Back to posts", posts_path, class:"btn btn-outline-secondary" %>
  </div>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>
<% if can? :manage, Post.new %>
  <%= link_to "New post", new_post_path , class:"btn btn-outline-primary"%>
<% end %>
<div class='row d-flex col-12 ' id="posts">
  <% @posts.each do |post| %>
    <div class="card col-6 p-4 m-2">
      <%= render post %>
      <p>
        <%= link_to "Show this post", post, class:'btn btn-info' %>
      </p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="card col-6 p-4">
  <h1>New post</h1>

  <%= render "form", post: @post %>

  <br>

  <div>
    <%= link_to "Back to posts", posts_path, class:"btn btn-outline-secondary" %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="card col-6 p-4">
  <%= render @post %>

  <div class='d-flex gap-2'>
    <% if can? :update, @post  %>
      <%= link_to "Edit this post", edit_post_path(@post), class:"btn btn-outline-info" %>
      <%= button_to "Destroy this post", @post, method: :delete, class:"btn btn-outline-danger" %>
    <% end %>
    <%= link_to "Back to posts", posts_path, class:"btn btn-outline-secondary" %>
  </div>
</div>

app/views/roles/index.html.erb
<table class="table">
  <thead>
  <%= link_to "New Permission", new_permission_path, class:"btn btn-info" %>
    <tr>

      <th scope="col">Role</th>
      <th>Resource</th>
      <th>Privilege Level</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <th scope="row"><%= role.name %></th>
      </tr>
        <% role.permissions.each do |permission| %>
        <tr>
          <td></td>
          <td><%= permission.subject_class %></td>
          <td><%= permission.action %></td>
          <td><%= link_to "Edit Permission", edit_permission_path(permission), class:'btn btn-info'  %></td>
        </tr>
        <% end %>
    <% end %>
    </tr>
  </tbody>
</table>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light ">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">AuthApp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <% if current_user %>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path,
                data: {
                "turbo-method": :delete
                }, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <a href="" class='nav-link bg-success btn btn-sm text-light' ><i> <%= current_user.name.capitalize %></i></a>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Log In', new_user_session_path, class:'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="form-group mt-2">
    <%= form.label :role, style: "display: block" %>
    <%=form.select :role_id, options_from_collection_for_select(@roles, 'id', 'name', user.role_id),
                                              {}, class:'form-control',
                                              required: true %>
  </div>

  <div class="form-group mt-2">
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password, class:"form-control" %>
  </div>
  <div class="form-group my-2">
    <%= form.submit class:"btn btn-primary btn-sm" %>
    <%= link_to 'Back', users_path, class:"btn btn-sm btn-outline-secondary" %>

  </div>
<% end %>

app/views/users/edit.html.erb
<div class="card">
  <div class="card-header">
    <h6> Edit User</h6>
  </div>
  <div class="mx-3">
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>

<%= link_to 'Back', root_path, class:"btn btn-sm btn-outline-secondary" %>

<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Email</th>
      <th scope="col">Role</th>
      <th scope="col">Created at</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <th scope="row"><%= user.id  %> </th>
      <td> <%= user.email %> </td>
      <td> <%= user.name %> </td>
      <td> <%= user.created_at %> </td>
      <td> <%= link_to 'Edit', edit_user_path(user), class:"btn btn-sm btn-outline-info" %></td>

    </tr>
  <% end %>
  </tbody>
</table>